[I18N][14.0] account: improve Incoterms Vietnamese translation
tvtma/odoo pull request #199
Opened 2022-03-14 08:13 UTC by thanhluan240287

Description of the issue/feature this PR addresses:
- Dịch lại phần Điều khoản thương mại
Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-17 01:20 UTC, davidtranhp commented
Hồi xưa anh làm xuất nhập khẩu mấy năm nhưng giao dịch người Việt với nhau cũng chỉ nói CIF, FOB, v.v. Gặp các thày giáo vác các thuật ngữ đã dịch ra là anh em không hiểu gì luôn.

2022-03-17 01:21 UTC, davidtranhp commented
Cái này đổi lại toàn bộ phần dịch thành nội dung không dịch (dùng nguyên gốc thuật ngữ tiếng Anh) giúp anh nhé.

2022-03-17 01:22 UTC, thanhluan240287 commented
> Cái này đổi lại toàn bộ phần dịch thành nội dung không dịch (dùng nguyên gốc thuật ngữ tiếng Anh) giúp anh nhé.

Vâng anh. Em thấy Odoo dịch nhưng sai sai nên em dịch lại ạ. Để em bỏ phần dịch của Odoo đi ạ

2022-03-22 07:03 UTC, davidtranhp requested changes

2022-03-22 07:03 UTC, davidtranhp commented on addons/account/i18n/vi.po
> +msgstr ""
Đưa nội dung gốc vào nội dung dịch để khi load translation cưỡng bức thì có thể fix được các thuật ngữ đã dịch sai. Nếu không thì phải đi từng database để sửa thủ công.

2022-03-22 07:04 UTC, thanhluan240287 commented on addons/account/i18n/vi.po
> +msgstr ""
vâng, để em sửa lại ạ

2022-03-22 23:16 UTC, merged