[FIX][14.0] purchase: Wrong statistics RFQs Sent Last 7 Days
tvtma/odoo pull request #231
Opened 2022-03-29 03:31 UTC by hoangtiendung070797

Task: [15817](https://viindoo.com/web#id=15817&action=409&active_id=158&model=project.task&view_type=form&cids=1&menu_id=289)
Ticket: [5298](https://viindoo.com/web#active_id=16&cids=1&id=5298&menu_id=777&model=helpdesk.ticket&view_type=form)

PR xử lý lỗi thống kê RFQ đã gửi trong 7 ngày qua
Vấn đề: trong câu query đếm số RFQ đã gửi không so sánh với các giá trị dịch sang các ngôn ngữ khác

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-03-29 04:10 UTC, davidtranhp requested changes

2022-03-29 04:10 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
Như này có được không?
```suggestion
                     AND v.old_value_char IN = _( 'RFQ')
                     AND v.new_value_char IN = _('RFQ Sent')
```

2022-03-29 05:03 UTC, hoangtiendung070797 commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
> Như này có được không?

@davidtranhp em nghĩ như này không được anh ạ, vì nếu dùng như này khi ở tiếng việt thì chỉ so sánh với tên 'Y/c báo giá' anh ạ còn 'RFQ' sẽ sót
cc @royleviindoo

2022-03-29 05:45 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
Bổ sung dịch cho 2 cái này chắc phải được chứ nhỉ?

2022-03-29 05:46 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
Em thử test giúp anh cái này nhé: https://github.com/odoo/odoo/pull/87426

Anh code chay, chưa test.

2022-03-29 06:16 UTC, hoangtiendung070797 commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
@davidtranhp em thử và không được anh ạ, mình truyền _('RFQ') thì sẽ chỉ lấy giá trị dịch theo ngôn ngữ người dùng hiện tại thôi anh ạ. Em gửi video bên dưới

https://user-images.githubusercontent.com/41574005/160545657-7e658116-1642-4776-847a-8b7c6319f478.mp4

2022-03-29 06:16 UTC, hoangtiendung070797 commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
cc @royleviindoo

2022-03-29 06:37 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
Chú bổ sung dịch tiếng Việt cho PR đó chưa?

2022-03-29 06:39 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
Ví dụ chỗ
```
#. module: purchase
#: model:ir.model.fields.selection,name:purchase.selection__purchase_order__state__draft
#, python-format
msgid "RFQ"
msgstr "Y/c báo giá"
```
phải thay bằng 
```
#. module: purchase
#: code:addons/purchase/models/purchase.py:0
#: model:ir.model.fields.selection,name:purchase.selection__purchase_order__state__draft
#, python-format
msgid "RFQ"
msgstr "Y/c báo giá"
```

2022-03-29 06:39 UTC, hoangtiendung070797 commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
> Chú bổ sung dịch tiếng Việt cho PR đó chưa?

@davidtranhp em lấy nhánh của anh bên trên về test ạ

2022-03-29 06:41 UTC, hoangtiendung070797 commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
để em kiểm tra lại ạ

2022-03-29 06:42 UTC, royleviindoo commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
Vấn đề gặp phải do đa ngôn ngữ anh ạ
Ví dụ
PO1: User 1 dùng tiếng Việt để đổi giai đoạn thì tracking sẽ lưu giá trị `Yêu cầu báo giá`
PO2: User 2 dùng tiếng Anh để đổi giai đoạn thì tracking sẽ lưu giá trị `RFQ`
Nhưng khi User 3 đang dùng tiếng Anh, thì cách code của anh sẽ chỉ lấy được PO2, còn PO1 thì không lấy được anh ạ

2022-03-29 06:49 UTC, hoangtiendung070797 commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
@davidtranhp em thử rồi không được anh ạ, _('RFQ') chỉ cho ra giá trị theo ngôn ngữ người dùng hiện tại ạ nên query kia sẽ không hết được bản ghi của mail_tracking_value ạ

2022-03-29 07:21 UTC, davidtranhp commented on addons/purchase/models/purchase.py
> +                     AND v.new_value_char IN %s
OK

2022-04-13 09:46 UTC, hoangtiendung070797 commented
@royleviindoo em có làm PR `https://github.com/odoo/odoo/pull/88635` cho odoo ạ

2022-04-20 02:59 UTC, royleviindoo commented
@hoangtiendung070797 rebase giúp anh nhé

2022-04-20 03:07 UTC, hoangtiendung070797 commented
> @hoangtiendung070797 rebase giúp anh nhé

@royleviindoo dạ vâng anh

2022-04-22 04:49 UTC, royleviindoo approved these changes

2022-04-22 05:43 UTC, merged