[I18N] base: fix file translation
tvtma/odoo pull request #298
Opened 2022-05-14 09:25 UTC by davidTAGit

Description of the issue/feature this PR addresses:
https://viindoo.com/web#id=6151&model=helpdesk.ticket&view_type=form&cids=1&menu_id=89

Cập nhật file dịch

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-05-16 05:07 UTC, davidtranhp requested changes
Vẫn chưa hoàn hảo ở 2 chỗ `%s per Unit` và `Unit per %s` nhưng anh nghĩ thế này vẫn tốt hơn.

Có thể đặt câu hỏi cho bên Tư vấn và bên QA/QC để xem các bên đó có gợi ý gì tốt hơn không

2022-05-16 05:07 UTC, davidtranhp commented on odoo/addons/base/i18n/vi.po
> +msgstr "Đơn vị tiền tệ của tỷ giá 1 đối với tỷ giá của đơn vị tiền tệ"
```suggestion
msgstr "Tỷ giá của tiền tệ có tỷ giá 1 so với tỷ giá của tiền tệ hiện hành"
```

2022-05-16 05:07 UTC, davidtranhp commented on odoo/addons/base/i18n/vi.po
> +msgstr "Đây là đơn vị tiền tệ của công ty bạn."
```suggestion
msgstr "Đây là tiền tệ của công ty bạn."
```

2022-05-16 05:07 UTC, davidtranhp commented on odoo/addons/base/i18n/vi.po
> +msgstr "Giá mỗi %s"
```suggestion
msgstr "Tỷ giá cho mỗi %s"
```

2022-05-16 05:07 UTC, davidtranhp commented on odoo/addons/base/i18n/vi.po
> +msgstr "Bạn không thể giảm số chữ số thập phân của đơn vị tiền tệ đã được sử dụng trên một bút toán."
```suggestion
msgstr "Bạn không thể giảm số chữ số thập phân của tiền tệ đã được sử dụng ở bút toán kế toán."
```

2022-05-16 06:04 UTC, davidTAGit commented
Dạ vâng anh @davidtranhp

2022-05-16 06:30 UTC, davidTAGit commented
Theo em %s per Unit sẽ dịch là: Tỷ giá 1 / %s thì mọi người dễ hiểu luôn ạ @davidtranhp

2022-05-18 03:41 UTC, davidtranhp commented
> Theo em `%s per Unit` sẽ dịch là: `Tỷ giá 1 / %s` thì mọi người dễ hiểu luôn ạ @davidtranhp

OK, cho anh xin cái clip nhé.

2022-05-18 04:04 UTC, davidTAGit commented
Em gửi anh @davidtranhp clip khi module được cập nhật file dịch

https://user-images.githubusercontent.com/99851330/168954811-2d46a842-5bd5-4eb3-b085-c8b3ac6901a3.mp4

2022-05-18 04:52 UTC, merged