[I18N] [14.0] Calendar: Translate some confusing words
tvtma/odoo pull request #321
Opened 2022-05-27 03:50 UTC by vuquang11

Description of the issue/feature this PR addresses: https://viindoo.com/web#active_id=6&cids=1&id=1723&menu_id=777&model=helpdesk.ticket&view_type=form

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-05-27 04:05 UTC, vietphuong10 commented on addons/calendar/i18n/vi.po
> +msgstr "Tuần đầu tiên trong tháng"
```suggestion
msgstr "Tuần đầu tiên"
```
 Bên ngoài là mục trong tháng rồi thì chỗ này chỉ cần để như này thôi. Tương tự mấy chỗ bên dưới nhé

2022-05-27 04:07 UTC, vuquang11 commented on addons/calendar/i18n/vi.po
> +msgstr "Tuần đầu tiên trong tháng"
vâng a

2022-05-27 14:19 UTC, vietphuong10 approved these changes

2022-06-01 04:00 UTC, davidtranhp requested changes

2022-06-01 04:00 UTC, davidtranhp commented on addons/calendar/i18n/vi.po
> +msgstr "Thứ trong Tháng"
Cái này là nhãn trên form ở chỗ chọn date hay day. Vẫn nên giữ nguyên là "Ngày trong Tháng"
```suggestion
msgstr "Ngày trong Tháng"
```

2022-06-01 04:03 UTC, davidtranhp requested changes
Như này thì khi ghép vào thằng sau nó đọc sẽ dễ hiểu hơn.

2022-06-01 04:03 UTC, davidtranhp commented on addons/calendar/i18n/vi.po
> +msgstr "Tuần đầu tiên"
Anh nghĩ là thế này thì khi ghép với thằng đằng sau đọc sẽ "trơn mồm" hơn
```suggestion
msgstr "Tuần đầu"
```
Tuần đầu Thứ Hai
Tuần đầu Thứ Ba

2022-06-01 04:03 UTC, davidtranhp commented on addons/calendar/i18n/vi.po
> +msgstr "Tuần thứ 4"
```suggestion
msgstr "Tuần 4"
```

2022-06-01 04:03 UTC, davidtranhp commented on addons/calendar/i18n/vi.po
> +msgstr "Tuần gần nhất"
```suggestion
msgstr "Tuần cuối"
```

2022-06-01 04:03 UTC, davidtranhp commented on addons/calendar/i18n/vi.po
> +msgstr "Tuần thứ 2"
```suggestion
msgstr "Tuần 2"
```

2022-06-01 04:03 UTC, davidtranhp commented on addons/calendar/i18n/vi.po
> +msgstr "Tuần thứ 3"
```suggestion
msgstr "Tuần 3"
```

2022-06-01 04:09 UTC, vuquang11 commented on addons/calendar/i18n/vi.po
> +msgstr "Thứ trong Tháng"
Đây anh ạ, lúc mình chọn day thì nó cho mình chọn thứ mấy trong tuần, nên em dịch ra là thứ trong tuần 
![253969](https://user-images.githubusercontent.com/55990739/171325348-77f37377-1891-42d2-a91c-afd909589f92.png)

2022-06-02 01:34 UTC, vuquang11 commented on addons/calendar/i18n/vi.po
> +msgstr "Thứ trong Tháng"
@davidtranhp Anh ơi nếu để "Ngày trong tháng" thì nếu chuyển sang tiếng việt thì cả date of month và day of month là ngày trong tháng, thì vẫn nên để "Thứ trong tháng" anh nhỉ.

2022-06-03 03:36 UTC, davidtranhp commented on addons/calendar/i18n/vi.po
> +msgstr "Thứ trong Tháng"
Label của trường thì em dịch là "Ngày trong tháng". Còn 2 option của nó thì một cái là "Ngày trong tháng", cái kia là "Thứ trong tháng".

Chỉnh lại cả các chỗ anh comment ở dưới nữa nhé.

2022-06-03 03:38 UTC, vuquang11 commented on addons/calendar/i18n/vi.po
> +msgstr "Thứ trong Tháng"
Vâng ạ

2022-06-03 07:53 UTC, merged