[FIX] [14.0] hr_timesheet: Adding translation
tvtma/odoo pull request #498
Opened 2022-09-01 02:32 UTC by minhthuy145

Description of the issue/feature this PR addresses:

Current behavior before PR:
- Ticket: [7814](https://viindoo.com/web#id=7814&menu_id=89&cids=1&model=helpdesk.ticket&view_type=form)

Desired behavior after PR is merged:
- `Số ngày` -> `Số giờ`

--
I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

2022-09-14 07:40 UTC, davidtranhp requested changes

2022-09-14 07:40 UTC, davidtranhp commented on addons/hr_timesheet/i18n/vi.po
> +"                                <span class=\"text-nowrap\" attrs=\"{'invisible' : [('encode_uom_in_days', '=', False)]}\">Số giờ đã dùng cho Nhiệm vụ con</span>"
```suggestion
"                                <span class=\"text-nowrap\" attrs=\"{'invisible' : [('encode_uom_in_days', '=', False)]}\">Số Ngày đã dùng cho Nhiệm vụ con</span>"
```

2022-09-14 07:40 UTC, davidtranhp commented on addons/hr_timesheet/i18n/vi.po
> +"<span class=\"text-nowrap\" attrs=\"{'invisible' : [('encode_uom_in_days', '=', True)]}\">Số giờ đã dùng cho Nhiệm vụ con</span>\n"
```suggestion
"<span class=\"text-nowrap\" attrs=\"{'invisible' : [('encode_uom_in_days', '=', True)]}\">Số Giờ đã dùng cho Nhiệm vụ con</span>\n"
```

2022-09-21 01:23 UTC, minhthuy145 commented on addons/hr_timesheet/i18n/vi.po
> +"                                <span class=\"text-nowrap\" attrs=\"{'invisible' : [('encode_uom_in_days', '=', False)]}\">Số giờ đã dùng cho Nhiệm vụ con</span>"
> 

Dạ em sửa lại rồi ạ. Em cảm ơn anh @davidtranhp :>

2022-10-14 15:08 UTC, merged