[I18N][15.0] website_hr_recruitment: improve vietnamese translation
tvtma/odoo pull request #514
Opened 2022-09-08 02:11 UTC by huy97852

Description of the issue/feature this PR addresses:

Current behavior before PR:

- [issues#445](https://github.com/Viindoo/odoo/issues/445)

Desired behavior after PR is merged:

* change field name to CamelCase format
* other small change 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-14 07:59 UTC, davidtranhp requested changes

2022-09-14 07:59 UTC, davidtranhp commented on addons/website_hr_recruitment/i18n/vi.po
> +msgstr "Công việc Quản trị"
```suggestion
msgstr "Công việc Hành chính"
```

2022-09-14 07:59 UTC, davidtranhp commented on addons/website_hr_recruitment/i18n/vi.po
> +msgstr "Tất cả Nhân viên"
```suggestion
msgstr "Tất cả Văn phòng"
```

2022-09-14 07:59 UTC, davidtranhp commented on addons/website_hr_recruitment/i18n/vi.po
> +"Tạo mới các trang việc làm từ <strong><i>+Mới</i></strong>nút trên góc "
`nút Mới` chứ sao lại là `Mới nút`???
```suggestion
"Tạo mới các trang việc làm từ nút <strong><i>+Mới</i></strong>trên góc "
```

2022-09-14 07:59 UTC, davidtranhp commented on addons/website_hr_recruitment/i18n/vi.po
>  "phải."
Cần mở phần mềm ra coi để dịch cho chuẩn
```suggestion
"phải bên trên."
```

2022-09-14 07:59 UTC, davidtranhp commented on addons/website_hr_recruitment/i18n/vi.po
> +msgstr "Tối ưu tìm kiếm"
Như này chuẩn hơn vì SEO giờ là một thuật ngữ phổ biến. Kiểu như mọi người hay nói "đàn piano" chứ ít người nói "đàn dương cầm"
```suggestion
msgstr "Tối ưu SEO"
```

2022-09-14 07:59 UTC, davidtranhp commented on addons/website_hr_recruitment/i18n/vi.po
> +msgstr "Tên tìm kiếm"
```suggestion
msgstr "Tên cho SEO"
```

2022-09-14 07:59 UTC, davidtranhp commented on addons/website_hr_recruitment/i18n/vi.po
> +msgstr "Những điều tuyệt vời về công việc này"
```suggestion
msgstr "Có gì tuyệt vời ở công việc này?"
```

2022-09-14 08:55 UTC, huy97852 commented on addons/website_hr_recruitment/i18n/vi.po
> +"Tạo mới các trang việc làm từ <strong><i>+Mới</i></strong>nút trên góc "
Dạ cái này em dịch sót ạ

2022-09-14 08:58 UTC, huy97852 commented on addons/website_hr_recruitment/i18n/vi.po
>  "phải."
dạ vâng ạ

2022-09-14 08:59 UTC, huy97852 commented on addons/website_hr_recruitment/i18n/vi.po
> +msgstr "Tối ưu tìm kiếm"
Vâng ạ

2022-09-22 08:05 UTC, davidtranhp requested changes
Xong 2 cái này là merge được

2022-09-22 08:05 UTC, davidtranhp commented on addons/website_hr_recruitment/i18n/vi.po
> +msgstr "Phát triển Cá nhân"
```suggestion
msgstr "Phát triển Bản thân"
```

2022-09-22 08:05 UTC, davidtranhp commented on addons/website_hr_recruitment/i18n/vi.po
> +msgstr "Các Vị trí đang Tuyển Dụng"
```suggestion
msgstr "Chúng tôi đang tuyển dụng"
```

2022-09-22 08:06 UTC, merged