[I18N][15.0] mrp : improve vietnamese translation
tvtma/odoo pull request #518
Opened 2022-09-09 04:20 UTC by huy97852

Description of the issue/feature this PR addresses:

Current behavior before PR:

- [issues#445](https://github.com/Viindoo/odoo/issues/445)

Desired behavior after PR is merged:

* change "Năng lực sản xuất" in workcenter traslation -> "Khu vực sản xuất"
* change BOM -> "Định mức nguyên liệu"
* change field name to CamelCase format
* other small change 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2022-09-19 11:17 UTC, davidtranhp requested changes
Nhiều sạn quá.

2022-09-19 11:17 UTC, davidtranhp commented on addons/mrp/i18n/vi.po
> +msgstr "Năng lực Sản xuất Dự trù"
```suggestion
msgstr "Năng lực Sản xuất Dự phòng"
```

2022-09-19 11:17 UTC, davidtranhp commented on addons/mrp/i18n/vi.po
> +msgstr "Định mức Nguyên liệu Biến thể Bản phẩm"
```suggestion
msgstr "BoM Biến thể Sản phẩm"
```

2022-09-19 11:17 UTC, davidtranhp commented on addons/mrp/i18n/vi.po
> +msgstr "Báo cáo Cấu trúc Định mức Nguyên liệu"
BoM là thuật ngữ phổ biến với người làm sản xuất nên các chỗ viết tắt ở gốc thì cũng không cần dịch đầy đủ.
```suggestion
msgstr "Báo cáo Cấu trúc BoM"
```

2022-09-19 11:17 UTC, davidtranhp commented on addons/mrp/i18n/vi.po
> +msgstr "Chia sẻ Kinh phí (%)"
Cost: Chi phí
Expense: Chi tiêu / Kinh phí
Spending: Chi tiêu
```suggestion
msgstr "Chia sẻ Chi phí (%)"
```

2022-09-19 11:17 UTC, davidtranhp commented on addons/mrp/i18n/vi.po
> +msgstr "Lý do"
Gốc của nó đang đúng
```suggestion
msgstr "Lý do Mất năng suất"
```

2022-09-20 03:52 UTC, huy97852 commented on addons/mrp/i18n/vi.po
> +msgstr "Lý do"
> Nhiều sạn quá.

dạ PR này em vẫn đang sửa lại ạ em quên không để wip

2022-10-25 04:50 UTC, leotranviindoo commented on addons/mrp/i18n/vi.po
> +"cần quản trị viên duyệt trước"
Câu dịch cũ đang chuẩn, chú dịch lại xong anh đọc chả hiểu gì? manufacturing users đang dịch là người thực hiện sản xuất <= câu này có gì sai mà phải dịch lại thành người dùng?

2022-10-25 04:53 UTC, leotranviindoo commented on addons/mrp/i18n/vi.po
> +"Năng lực sản xuất dự trù có thể được thay thế thực hiện cho lệnh này để nhanh"
Trên thì dịch thành Dự phong, dưới lại là dự trù là sao em?

2022-10-25 04:53 UTC, leotranviindoo commented on addons/mrp/i18n/vi.po
> +msgstr "Định mức Nguyên liệu"
Bills of Material hay BoM hay BOM là một thuật ngữ trong Sản xuất. Do đó cần thống nhất khi dịch thuật ngữ này trên toàn hệ thống. Chỗ thì Định mức nguyên liệu, chỗ thì Định mức Nguyên vật liệu, chỗ thì Định mức Vật liệu???

2022-10-25 04:53 UTC, leotranviindoo commented
Sai thuật ngữ và nghiệp vụ rất nhiều. Anh close PR nhé

2022-10-25 04:53 UTC, closed without merging